export const SECTION_TITLE = "Abgeschlossene Weiterbildung";

export const DESCRIPTION = {
    AS: "als Fullstack Web Developer",
    EDUCATIONAL_INSTITUTION: "bei der velpTEC GmbH",
    EDUCATIONAL_INSTITUTION_LINK: "https://velptec.de/",
    PERIOD_OF_TIME: "Unterrichtsdauer: 29 Wochen (1160 Unterrichtseinheiten)",
    DEGREE: "Abschluss: Zertifikat",
    RESULT: "Gesamtergebnis der Prüfungsleistung:",
    RESULT_PERCENTAGE: "95%"
};

export const MODULES = [
    {
        id: 1,
        title: "HTML und CSS",
        imageUrl: "html",
        content: [
            "Grundlegender Aufbau von HTML-Dokumenten",
            "Der sichtbare Bereich eines HTML-Dokuments",
            "HTML-Elemente für Seitenstrukturierung",
            "Tabellen und Hyperlinks",
            "Grafiken und Multimedia",
            "HTML-Formulare und interaktive Elemente",
            "Einführung in Cascading Stylesheets (CSS)",
            "Selektoren von CSS",
            "Vererbung und Kaskade in CSS",
            "Box-Modell von CSS",
            "Positionierung in CSS",
            "Transferaufgaben",
            "Responsive Layouts mit CSS",
            "Stylen mit CSS",
            "Textgestaltung mit CSS",
            "Gestalten von Listen, Tabellen und Grafiken mit CSS",
            "Transformieren von Elementen mit CSS",
            "Stylen von HTML-Formularen mit CSS",
            "Testen und Organisieren",
            "Einführung in dynamische Websites via JavaScript"
        ]
    },
    {
        id: 2,
        title: "Python3",
        imageUrl: "python3",
        content: [
            "Installation und Einrichtung von Python",
            "Python im interaktiven Modus",
            "Grundlegende Programmierkonzepte",
            "Datenstrukturen",
            "Paradigmen",
            "Anweisungen",
            "Python-Skripte",
            "Standard-Datentypen",
            "Kontrollstrukturen",
            "Funktionen",
            "Sequenzen, Mengen und Generatoren",
            "Dictionaries",
            "Ein-und Ausgabe",
            "Definition von Klassen",
            "Klassenbibliotheken in Modulen",
            "Objektorientiertes Modellieren",
            "Textverarbeitung",
            "Systemfunktionen",
            "Grafische Benutzungsoberflächen mit tkinter",
            "Layout, Grafik und Event-Verarbeitung",
            "Komplexe Benutzungsoberflächen",
            "Threads",
            "Finden und Vermeiden von Fehlern",
            "Dynamische Websites-CGI und WSGI",
            "Datenbanken",
            "Testen und Tuning",
            "XML und JSON",
            "Modellieren mit Kellern, Schlangen und Graphen",
            "Benutzungsoberflächen mit QT und Multimediaanwendungen mit QT",
            "Einführung in NumPy und Messdatenverarbeitung"            
        ]
    },
    {
        id: 3,
        title: "Java",
        imageUrl: "java",
        content: [
            "Installation und Einrichtung einer Java-Entwicklungsumgebung",
            "Funktionsweise von Verzweigungen",
            "Funktionsweise von Variablen mit primitivem Datentyp",
            "Funktionsweise von Operatoren",
            "Kompilieren von Java-Programmen",
            "Grundlagen der objektorientierten Programmierung",
            "Funktionsweise von Schleifen",
            "Funktionsweise von Funktionen",
            "Funktionsweise von Funktionen mit Rückgabewert",
            "Vererbung in objektorientierter Programmierung",
            "Arrays",
            "Abstrakte Methoden und Klassen",
            "Sichtbarkeit in objektorientierter Programmierung",
            "Listen",
            "Fehlerbehebung in Java",
            "Dateisystemzugriff in Java",
            "Anwendung von Listen und Arrays",
            "Fehlererkennung und Behebung in Java",
            "Grafische Benutzeroberflächen in Java",
            "Erstellen von Java-Bibliotheken",
            "Parallele Programmierung in Java",
            "Verwenden von Java-Bibliotheken",
            "Verwendung von SQL-Datenbanken in Java",
            "Erstellung von REST-APIs mit Java",
            "Anwendung von Java im Handel",
            "Anwendung von Java in wissenschaftlichem Rechnen",            
        ]
    },
    {
        id: 4,
        title: "JavaScript",
        imageUrl: "javascript",
        content: [
            "Sprachkern: Arbeiten mit variablen Datentypen und Arrays",
            "Sprachkern: Operatoren und Steuern des Ablaufs eines Programms",
            "Sprachkern: Arbeiten mit Schleifen und Funktionen",
            "Sprachkern: Reagieren auf Fehler",
            "Objektorientierte Programmierung mit JavaScript",
            "Arbeiten mit Objekten",
            "Extrahieren von Werten aus Arrays und Objekten",
            "Arbeiten mit Maps",
            "Funktionen als Refenrenztypen",
            "Dynamisches Verändern von Webseiten",
            "Arbeiten mit DOM",
            "Arbeiten mit Textknoten",
            "Verbinden von Arrays und Objekten",
            "Ereignisgesteuerte Programmierung",
            "Verstehen und Beeinflussen des Ereignisflusses",
            "Arbeiten mit Formularen",
            "Steuern des Browsers",
            "Lesen und Erkennen von Browserinformationen",
            "Nachladen von Inhalten",
            "Funktionale Programmierung",
            "Asynchrone Programmierung"
            
        ]
    },
    {
        id: 5,
        title: "Webentwicklung für Fullstack Entwickler",
        imageUrl: "webentwicklung",
        content: [
            "Grundlagen der Webentwicklung",
            "HTML und CSS in der Webentwicklung",
            "JavaScript in der Webentwicklung",
            "Webprotokolle und Webformate",
            "Web-APIs und Optimierung für Barrierefreiheit",
            "Single Page Application mit React",
            "Webarchitekturen und Programmiersprachen auf Serverseite",
            "Einführung in Node.js",
            "Webservices: SOAP, REST und GraphQL",
            "Datenbanken in der Webentwicklung",
            "Zusammenführen von Webservices und Datenbanken",
            "Unit Tests, Deployment und Hosting",
            "Datensicherheit und Datenschutz",
            "Übungen zu Datensicherheit und Datenschutz",
            "Einführung in git und Software Engineering",
            "Übungen zu git und Software Engineering",
            "Erstellen einer kompletten Webanwendung"
        ]
    },
    {
        id: 6,
        title: "Methodenkompetenz",
        imageUrl: "methodenkompetenz",
        content: [
            "VUKA",
            "Methoden und Kompetenzen im beruflichen Zusammenhang",
            "Kommunikation in Teams",
            "Kollaboratives Arbeiten mit verschiedenen Online-Tools",
            "Sozial- und Selbstkompetenz"
        ]
    },
];